image: docker:stable

variables:
  DOCKER_DRIVER: overlay2

services:
- docker:dind

before_script:
- docker info

build:
  stage: build
  script:
  - docker-compose up --build
  - docker-compose exec web bundle exec rake db:create db:schema:load assets:precompile